apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mayurkubesamples 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mayurkubesamples 
    spec:
      containers:
        - name: mayurkubesamples 
          image: indialends.azurecr.io/mayurkubesamples
          ports:
          - containerPort: 80